steps:
  gctsCloneRepository:
    host: '54.146.187.28'
    client: '100'
    abapCredentialsId: 'gCTS_source'
    repository: 'dreamer-nv-gcts03'
  gctsDeploy:
    host: '54.227.214.122'
    client: '100'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-gcts03'
