general:
  verbose: true
steps:
  setupCommonPipelineEnvironment:
    collectTelemetryData: false
  gctsDeploy:
    host: 'http://54.227.214.122:8000'
    client: '100'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-gcts03'
  gctsExecuteABAPUnitTests:
    host: 'http://54.227.214.122:8000'
    client: '100'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-gcts03'
  gctsRollback:
    host: 'http://54.227.214.122:8000'
    client: '100'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-gcts03'
